name: Build

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'package.json'
      - 'backend/**/*'
      - 'frontend/**/*'
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - 'package.json'
      - 'backend/**/*'
      - 'frontend/**/*'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: oven-sh/setup-bun@v1
        if: matrix.platform != 'windows-latest'
        with:
          bun-version: latest

      - uses: actions/setup-node@v1
        if: matrix.platform == 'windows-latest'
        with:
          node-version: '20.x'

      - uses: actions/checkout@v3

      - name: Install dependencies
        if: matrix.platform != 'windows-latest'
        run: cd frontend && bun install

      - name: Install dependencies (Windows)
        if: matrix.platform == 'windows-latest'
        run: cd frontend && npm install

      - name: Build
        if: matrix.platform != 'windows-latest'
        run: bun run build:bun

      - name: Build (Windows)
        if: matrix.platform == 'windows-latest'
        run: npm run build

      - name: Upload
        uses: actions/upload-artifact@v2
        if: matrix.platform != 'windows-latest'
        with:
          name: procchi_${{ matrix.platform }}
          path: backend/target/release/procchi

      - name: Upload (Windows)
        uses: actions/upload-artifact@v2
        if: matrix.platform == 'windows-latest'
        with:
          name: procchi_${{ matrix.platform }}
          path: backend/target/release/procchi.exe