name: Lint backend

on:
  push:
    paths:
      - '.github/workflows/lint-backend.yml'
      - 'package.json'
      - 'backend/**/*'
  pull_request:
    paths:
      - '.github/workflows/lint-backend.yml'
      - 'package.json'
      - 'backend/**/*'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
          
      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cargo format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path ./src-tauri/Cargo.toml --all -- --check

      - name: Cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path ./src-tauri/Cargo.toml --all -- -D warnings
